name: Docs Test

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# cancel previous tests if new commit is pushed to PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-docs:
    name: Test docs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./docs/package-lock.json

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci

      - name: Test build website
        working-directory: ./docs
        run: npm run build