name: Test Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - javascript/json-transform/**
      - javascript/json-transform-utils/**
      - javascript/monaco-json-transform/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# cancel previous tests if new commit is pushed to PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

        # -- json-transform build
      - name: setup json-transform build
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./javascript/json-transform/package-lock.json
      - name: install json-transform dependencies
        working-directory: ./javascript/json-transform
        run: npm ci
      - name: build json-transform
        working-directory: ./javascript/json-transform
        run: npm run build

        # -- json-transform-utils build
      - name: setup json-transform-utils build
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./javascript/json-transform-utils/package-lock.json
      - name: install json-transform-utils dependencies
        working-directory: ./javascript/json-transform-utils
        run: npm ci
      - name: build json-transform-utils
        working-directory: ./javascript/json-transform-utils
        run: npm run build

        # -- monaco-json-transform build
      - name: setup monaco-json-transform build
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./javascript/monaco-json-transform/package-lock.json
      - name: install monaco-json-transform dependencies
        working-directory: ./javascript/monaco-json-transform
        run: npm ci
      - name: build monaco-json-transform
        working-directory: ./javascript/monaco-json-transform
        run: npm run build

        # -- docs build
      - name: setup docs build
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./docs/package-lock.json
      - name: install docs dependencies
        working-directory: ./docs
        run: npm ci
      - name: build docs
        working-directory: ./docs
        run: npm run build