name: Java playground publish

on:
  push:
    branches: [ "main" ]
    paths:
      - java/playground/**

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          java-package: jdk
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Run tests with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          # build includes tests
          arguments: |
            :java:playground:build
            --console=plain
            --parallel
            -Dorg.gradle.parallel.intra=true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./java/playground
          push: true
          tags: |
            ghcr.io/nlighten-oss/json-transform-playground:latest