name: Publish Java json-transform

on:
  push:
    tags:
      - 'java-lib-*'  # Match tags
    branches:
      - main
    paths:
      - java/json-transform/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle

    - name: Extract version from tag
      id: get_version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        VERSION=${TAG_NAME#java-lib-}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build and publish to Maven Central
      run: ./gradlew publishAndReleaseToMavenCentral
      env:
        VERSION: "${{ env.VERSION }}"
        ORG_GRADLE_PROJECT_mavenCentralUsername: "${{ secrets.OSSRH_USERNAME }}"
        ORG_GRADLE_PROJECT_mavenCentralPassword: "${{ secrets.OSSRH_TOKEN }}"
        ORG_GRADLE_PROJECT_signingInMemoryKey: "${{ secrets.PGP_PRIVATE_KEY }}"
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: "${{ secrets.PGP_KEY_ID }}"
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: "${{ secrets.PGP_PASSPHRASE }}"