name: JavaScript json-transform-core Test

on:
  pull_request:
    branches:
      - main
    paths:
      - javascript/json-transform-core/**
# cancel previous tests if new commit is pushed to PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./packages/json-transform-core

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: './packages/json-transform-core/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
